### ISSUE TITLE
Añadir items como objetos ademas de componentes

### ISSUE THREAD

**Issue by joncolque** [CySidi/goten-react-list#5]
Si añado un ítem querría poder buscarlo o eliminarlo en el entorno donde estoy utilizando el goten-react-list.
Si por ejemplo quiero eliminar un ítem no solo debo eliminarlo dentro del goten-list sino afuera en el entorno del usuario y necesito saber que elemento se eliminó por lo tanto necesitaría una estructura con metadatos que me identifique que elemento es el que se esta manipulando desde el goten-list
poder hacer algo asi
```js
 this.refs[gotenListRef].addItem(
                    {
                        showName:"archivo.jpg",
                        metadata:{
                            id:453
                            ...
                        }
                    }
                )
```
Asi el goten-list muestra "archivo.jpg" y cuando "elimine" el item, sabré que item es por su id (o por la metadata que se maneje) dandole la posibilidad de eliminar dicho item al usuario.

**Comment by nicolas-meilan** [comment]
Proba usando el metodo onRemove, desde ahi podes obtener el componente que borras, ahora con respecto a lo de objetos, la lista funciona con componentes de react, tendrías que estructurarte a eso.

``` jsx
this.refs[gotenListRef].addItem(
    <Component />,
    {
        onSearch: component => this.method(component)
        onEdit: component => this.method(component)
        onRemove: component => this.yourRemoveMethod(component)
    }
)
```

Para ver ejemplos de uso podes ver el **README**, o revisar el archivo **./example/src/exampleGotenList.jsx**
